version: '3'

services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  locust-master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"
    environment:
      - LOCUST_MODE=master
    volumes:
      - ./locust:/mnt
    command: ["-f", "/mnt/locust-waitingRoom.py", "--master", "--host=http://host.docker.internal:8600"]

  locust-worker:
    image: locustio/locust
    depends_on:
      - locust-master
    environment:
      - LOCUST_MODE=worker
    volumes:
      - ./locust:/mnt
    command: ["-f", "/mnt/locust-waitingRoom.py", "--worker", "--master-host=locust-master"]

volumes:
  redis-data: