spring:
  application:
    name: flow-core
  data:
    redis:
        host: 127.0.0.1
        port: 6379


server:
  port: 8600


scheduler:
  enabled: true


---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790


scheduler:
  enabled: false

