spring:
  application:
    name: flow
  data:
    redis:
        host: 127.0.0.1
        port: 6379


server:
  port: 8600


---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790




